### ISSUE TITLE
Compile failure w/ base-4.7

### ISSUE THREAD

**Issue by hvr** [amarpotghan/crjdt-haskell#5]
The cabal file advertises compatiblity with `base >= 4.7 && < 5`, however GHC 7.8 disagrees:

```
Configuring component lib from crjdt-haskell-0.3.0...
Preprocessing library crjdt-haskell-0.3.0...

src/Data/Crjdt.hs:48:8:
    Could not find module ‘Data.Void’
    It is a member of the hidden package ‘void-0.7.2’.
    Perhaps you need to add ‘void’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

src/Data/Crjdt.hs:50:8:
    Could not find module ‘Data.Bifunctor’
    It is a member of the hidden package ‘bifunctors-5.4.2’.
    Perhaps you need to add ‘bifunctors’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

I've already revised the meta-data of the affected releases to use a tigher lower bound on `base`:

- https://hackage.haskell.org/package/crjdt-haskell-0.1.0.0/revisions/
- https://hackage.haskell.org/package/crjdt-haskell-0.2.0.0/revisions/
- https://hackage.haskell.org/package/crjdt-haskell-0.2.1/revisions/
- https://hackage.haskell.org/package/crjdt-haskell-0.3.0/revisions/

So there's no need to upload a new release only for the meta-data.

See also http://matrix.hackage.haskell.org/package/crjdt-haskell

**Comment by amarpotghan** [comment]
Thank you! I updated that in the master.
